"""empty message

Revision ID: 1732b75aa7b2
Revises: 7c16c044c7cc
Create Date: 2026-04-11 05:30:19.550589

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "1732b75aa7b2"
down_revision: Union[str, Sequence[str], None] = "7c16c044c7cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("categories_user_id_fkey"), "categories", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "categories", "users", ["user_id"], ["uid"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "categories", type_="foreignkey")
    op.create_foreign_key(
        op.f("categories_user_id_fkey"), "categories", "users", ["user_id"], ["uid"]
    )
    # ### end Alembic commands ###
