"""add name to budgets

Revision ID: 23a84e08b076
Revises: 64c0150b9a8e
Create Date: 2026-04-08 20:13:57.097429

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23a84e08b076"
down_revision: str | Sequence[str] | None = "28b088061135"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("budgets", sa.Column("name", sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("budgets", "name")
    # ### end Alembic commands ###
