"""empty message

Revision ID: 240f0315ae98
Revises: ae05d31ce48d
Create Date: 2026-04-02 01:20:47.154679

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "240f0315ae98"
down_revision: Union[str, Sequence[str], None] = "ae05d31ce48d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "expenses", "category_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "expenses", "category_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
