"""Set on_delete actions for Expense and Budget

Revision ID: 73da91ee514c
Revises: 240f0315ae98
Create Date: 2026-04-09 23:20:12.121005

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "73da91ee514c"
down_revision: Union[str, Sequence[str], None] = "240f0315ae98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("budgets_category_id_fkey", "budgets", type_="foreignkey")
    op.drop_constraint("budgets_user_id_fkey", "budgets", type_="foreignkey")
    op.create_foreign_key(
        "budgets_category_id_fkey",
        "budgets",
        "categories",
        ["category_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "budgets_user_id_fkey",
        "budgets",
        "users",
        ["user_id"],
        ["uid"],
        ondelete="CASCADE",
    )

    op.drop_constraint("expenses_category_id_fkey", "expenses", type_="foreignkey")
    op.drop_constraint("expenses_user_id_fkey", "expenses", type_="foreignkey")
    op.create_foreign_key(
        "expenses_category_id_fkey",
        "expenses",
        "categories",
        ["category_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "expenses_user_id_fkey",
        "expenses",
        "users",
        ["user_id"],
        ["uid"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("expenses_user_id_fkey", "expenses", type_="foreignkey")
    op.drop_constraint("expenses_category_id_fkey", "expenses", type_="foreignkey")
    op.create_foreign_key(
        "expenses_user_id_fkey", "expenses", "users", ["user_id"], ["uid"]
    )
    op.create_foreign_key(
        "expenses_category_id_fkey", "expenses", "categories", ["category_id"], ["id"]
    )

    op.drop_constraint("budgets_user_id_fkey", "budgets", type_="foreignkey")
    op.drop_constraint("budgets_category_id_fkey", "budgets", type_="foreignkey")
    op.create_foreign_key(
        "budgets_user_id_fkey", "budgets", "users", ["user_id"], ["uid"]
    )
    op.create_foreign_key(
        "budgets_category_id_fkey", "budgets", "categories", ["category_id"], ["id"]
    )
    # ### end Alembic commands ###
