"""empty message

Revision ID: 7c16c044c7cc
Revises: a516bf1b3209
Create Date: 2026-04-11 05:29:07.619652

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "7c16c044c7cc"
down_revision: Union[str, Sequence[str], None] = "a516bf1b3209"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
