"""empty message

Revision ID: 8026af70aee4
Revises: f3c0edd675a2
Create Date: 2026-04-11 01:07:53.186624

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8026af70aee4"
down_revision: Union[str, Sequence[str], None] = "f3c0edd675a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_category_user_name", "categories", ["user_id", "name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_category_user_name", "categories", type_="unique")
    # ### end Alembic commands ###
