"""empty message

Revision ID: a516bf1b3209
Revises: 8026af70aee4
Create Date: 2026-04-11 01:26:26.648864

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a516bf1b3209"
down_revision: Union[str, Sequence[str], None] = "8026af70aee4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_budgets_month_year"), "budgets", ["month_year"], unique=False
    )
    op.drop_constraint(op.f("uq_category_user_name"), "categories", type_="unique")
    op.create_unique_constraint(
        "uq_categories_name_user", "categories", ["user_id", "name"]
    )
    op.create_index(
        "idx_expenses_category_id", "expenses", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_expenses_transaction_date"),
        "expenses",
        ["transaction_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expenses_transaction_date"), table_name="expenses")
    op.drop_index("idx_expenses_category_id", table_name="expenses")
    op.drop_constraint("uq_categories_name_user", "categories", type_="unique")
    op.create_unique_constraint(
        op.f("uq_category_user_name"),
        "categories",
        ["user_id", "name"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_budgets_month_year"), table_name="budgets")
    # ### end Alembic commands ###
