"""empty message

Revision ID: e0812541ca96
Revises: 0820896632c6
Create Date: 2026-04-11 00:11:53.243092

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e0812541ca96"
down_revision: Union[str, Sequence[str], None] = "0820896632c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_budgets_user_category", "budgets", ["user_id", "category_id"], unique=False
    )
    op.create_index(
        "idx_budgets_user_month_year",
        "budgets",
        ["user_id", "month_year"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_user_category_month", "budgets", ["user_id", "month_year", "category_id"]
    )
    op.create_index("idx_categories_user_id", "categories", ["user_id"], unique=False)
    op.create_index(
        "idx_expenses_user_category",
        "expenses",
        ["user_id", "category_id"],
        unique=False,
    )
    op.create_index(
        "idx_expenses_user_date",
        "expenses",
        ["user_id", "transaction_date"],
        unique=False,
    )
    op.create_index("idx_users_email", "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_users_email", table_name="users")
    op.drop_index("idx_expenses_user_date", table_name="expenses")
    op.drop_index("idx_expenses_user_category", table_name="expenses")
    op.drop_index("idx_categories_user_id", table_name="categories")
    op.drop_constraint("uq_user_category_month", "budgets", type_="unique")
    op.drop_index("idx_budgets_user_month_year", table_name="budgets")
    op.drop_index("idx_budgets_user_category", table_name="budgets")
    # ### end Alembic commands ###
